### ISSUE TITLE
Modify model creator script to use a common format

### ISSUE THREAD

**Issue by cbdm** [cbdm/Implied_Scenarios#4]
Could modify `model_parser.py` to use a common format like YAML or JSON instead of the custom one we defined.
YAML seems like a good option!

For instance, `example_model.txt` could be changed to something like this:

```
model:
    title: Nuclear Power Plant
    init: init
    components:
        - P1
        - UR
        - NA
        - P2
    transitions:
        - init > Scen1
        - init > Scen2
    scenarios:
        Scen1:
            - P1 > UR : inc
            - P1 > NA : inc
            - P2 > UR : double
            - P2 > NA : double
        Scen2:
            - P2 > UR : double
            - P2 > NA : double
            - P1 > UR : inc
            - P1 > NA : inc
```
